### ISSUE TITLE
Send PR?

### ISSUE THREAD

**Issue by ghost** [denis-peshkov/TypeScriptDefinitionGenerator#10]
I just wanted to install `TypeScriptDefinitionGenerator`. Then I noticed your fork. Now I am not sure which to use... Thanks for your updates! You seem to be quite active!

Did you consider pushing your changes back to the [originating project](https://github.com/madskristensen/TypeScriptDefinitionGenerator)?

Especially [the commit which adds support for `byte`](https://github.com/denis-peshkov/TypeScriptDefinitionGenerator/commit/c541131528ea560e755e5b1a3261f83203b3b811#diff-13ef6cbffc8b860688bbbe7c45571206) seems very valuable.

**Comment by ghost** [comment]
Okay, just found issue https://github.com/madskristensen/TypeScriptDefinitionGenerator/issues/39 which you commented but no response from the author. That is disappointing. The missing "export" is also a big issue for me, so I decided to use your fork, which actually produces "importable" interfaces. Thanks again!

**Comment by denis-peshkov** [comment]
thx @LukeOwlclaw, if any improvements required, just notify me, I'll try to do when have free time
