### ISSUE TITLE
Guid is being converted to any and not string

### ISSUE THREAD

**Issue by warlock00** [denis-peshkov/TypeScriptDefinitionGenerator#14]
### Installed product versions
- Visual Studio: 2017 Pro
- This extension: 2.2.0.97

### Description
Guid is being converted to any and not string

### Steps to recreate
public Guid? MyId { get; ;set; }

### Current behavior
MyId?: any;

### Expected behavior
MyId?: string;

**Comment by warlock00** [comment]
If you put in invalid c# code as:
public GUID? MyId { get; ;set; }
or
public guid? MyId { get; ;set; }

Then the d.ts is correctly converted to
MyId?: string;

**Comment by denis-peshkov** [comment]
will fix

**Comment by warlock00** [comment]
Can confirm it works now 👍
